replicaCount: 1

#image:
#  registry: localhost:5000

resources:
  requests:
    memory: '200Mi'
    cpu: '250m'
  limits:
    memory: '300Mi'
    cpu: '1'


services:
  - name: smev-front
    type: NodePort
    ports:
    - name: smev-front
      port: 80
      nodePort: 30000
