replicaCount: 1

resources:
  requests:
    memory: '100Mi'
    cpu: '200m'
  limits:
    memory: '400Mi'
    cpu: '1'

services:
  - name: plugin-integration-adapter
    type: NodePort
    ports:
    - name: plugin-rest
      port: 7590
      targetPort: 7590
      nodePort: 31070
