replicaCount: 1

resources:
  requests:
    memory: '256Mi'
    cpu: '100m'
  limits:
    memory: '400Mi'
    cpu: '1'

services:
  - name: ws-intergation-adapter
    type: NodePort
    ports:
    - name: adapter-rest
      port: 7590
      targetPort: 7590
      nodePort: 31070
    - name: ws-adapter-web
      port: 7575
      targetPort: 7575
      nodePort: 31071
